version: '3.3'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    env_file:
      - ./.env
    restart: always

  web:
    container_name: django
    image: university_local_django
    build: .
    restart: always
    command: /usr/local/bin/gunicorn config.wsgi:application -w 2 -b :8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - web

#  celery:
#    build: ./code
#    command: celery worker --app=core --loglevel=info
#    volumes:
#      - .:/code
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
#    depends_on:
#      - web
#      - redis

  redis:
    image: redis:5.0

volumes:
  postgres_data:
  static_value:
  media_value:
